In [9]:
#0-D ARRAYS
import numpy as np
arr = np.array(10)
print(arr)


10


In [31]:
#1-D ARRAYS
import numpy as np
arr = np.array([10,20,30])
print(arr)


[10 20 30]


In [11]:
#2-D ARRAYS
import numpy as np
arr = np.array([[10,20,30],[40,50,60]])
print(arr)


[[10 20 30]
 [40 50 60]]


In [21]:
#3-D ARRAYS with 2D-ARRAYS
import numpy as np
arr = np.array([[[10,20,30],[40,50,60]],[[1,2,3],[4,5,6]]])
print(arr)


[[[10 20 30]
  [40 50 60]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [22]:
#TO CHECK DIMENTIONS OF ARRAY
import numpy as np

# 0-D array (scalar)
a = np.array(42)

# 1-D array
b = np.array([1, 2, 3, 4, 5])

# 2-D array
c = np.array([[1, 2, 3], [4, 5, 6]])

# 3-D array
d = np.array([[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [23]:
#TO CHECK INDEX FOR 1D ARRAY
import numpy as np
arr = np.array([1,2,3,4])
print(arr[1])

2


In [24]:
#GET THE 2ND AND 3RD ELEMENT INDEX AND ADD THEM
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [25]:
#FROM 2 ARRAYS GET INDEX
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0,1])

2


In [29]:
#SLICING OPERATIONS 
#SLICE ELEMENTS FROM INDEX 1 TO INDEX 5      
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [30]:
#start index has not been mentioned if we dont pass start its consodered 0
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:5])

[1 2 3 4 5]


In [32]:
#if both are not mentioned
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:])

[1 2 3 4 5 6 7]


In [34]:
#slice elements from index 4 to the end of the array
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [35]:
#slicce from the index 3 from the end to index 1 from end
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [50]:
#USING STEP VALUE TO DETERMINE THE STEP OF SLICING       #([START,END,STEP])
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5:2])

[2 4]


In [38]:
#RETURN EVERY OTHER ELEMENT FROM THE ENTIRE ARRAY
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [1]:
#SLICING 2D ARRAY
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [6]:
#EG
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(arr[1,2])

6


In [5]:
#EG                                                        #START END STEP
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(arr[0:2:])

[[1 2 3]
 [4 5 6]]


In [9]:
#
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
col_slice = arr[:,1:3]                                       #:, means all rows are selected
print(col_slice)

[[2 3]
 [5 6]
 [8 9]]
